import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/Header/Header";
import Footers from "@/components/Footers/Footers";
import Session from "@/components/sessionProviders/SessionProvider";
import Shopheader from "@/components/shop/Shopheader";
import SmoothScroll from "@/components/SmothScroll/smoothscroller";
import Head from "next/head";

const Urbanistt = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "Shopping Mart",
    default: "Shopping Mart A Place For All",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname();

  return (
    <html lang="en">
      <>
      <Head>
        <meta name="google-site-verification" content="coKkiJhG8EmTc2KhZf2O3vBpvGdtoEm40jJgGJihVaA" />
      </Head>
        <body
          className={`${Urbanistt.className} bg-main-bg w-full bg-slate-100   text-darkText `}
        >
          <Session>
            {/* <SmoothScroll> */}
            <Header />
            {/* {pathname === "/category/home" && <Shopheader />} */}
            {children}
            <Footers />
            {/* </SmoothScroll> */}
          </Session>
        </body>
      </>
    </html>
  );
}
